### ISSUE TITLE
change corpus without discarding locked lines

### ISSUE THREAD

**Issue by muello** [vilmibm/trunkless#3]
beautiful app!

it'd be nice if you could generate some lines, lock some of them, then switch corpus and hit 'go' and have the locked lines still stay in place. tricky to implement?

**Comment by vilmibm** [comment]
that would be awesome. I think that is a very elegant solution to combining corpora that never occurred to me!

I will think it through but I don't think it would be that onerous.

**Comment by vilmibm** [comment]
This is shipped, now. The corpus selector will promptly regenerate all unpinned lines with the new corpus -- no more form submit and reload.
